--------- Production mode ---------
---- Rendered error ----
Random message for this exception
---- Logger error ----
Random message for this exception
--------- Debug mode ---------
---- Rendered error ----
Random message for this exception
Traceback (most recent call last):
  File "{TESTS_PROJECT_FOLDER}/src/tests/internal/test_rendering.py", line 263, in _printError
    1 / 0  # Ooops !
ZeroDivisionError: division by zero
---- Logger error ----
Random message for this exception
Traceback (most recent call last):
  File "{TESTS_PROJECT_FOLDER}/src/tests/internal/test_rendering.py", line 263, in _printError
    1 / 0  # Ooops !
ZeroDivisionError: division by zero